name: $(Rev:r:)

jobs:
  - job: Test
    pool:
      vmImage: "macOS-latest"

    steps:
      - task: CmdLine@2
        displayName: Install
        inputs:
          script: |
            npm ci

      - task: CmdLine@2
        displayName: Build
        inputs:
          script: |
            npm run ng -- build

      - task: CmdLine@2
        displayName: Test
        inputs:
          script: |
            npm run ng --  test --watch=false

      - task: SonarQubePrepare@4
        displayName: Setup sonar
        inputs:
          SonarQube: "sonarqube-dev-guild"
          scannerMode: "CLI"
          configMode: "file"
      - task: SonarQubeAnalyze@4
        displayName: Run analyze

      - task: SonarQubePublish@4
        displayName: Run publish
        inputs:
          pollingTimeoutSec: "300"
