name: $(Rev:r:)

jobs:
  - job: Test
    pool:
      vmImage: "macOS-latest"
    steps:
      - task: CmdLine@2
        displayName: Install
        inputs:
          script: |
            npm ci

      - task: CmdLine@2
        displayName: Build
        inputs:
          script: |
            npm run build

      - task: CmdLine@2
        displayName: Test
        inputs:
          script: |
            ng test --watch=false
